### ISSUE TITLE
QR Code inventory does not display comments

### ISSUE THREAD

**Issue by ArmannDeol** [CMPUT301W23T44/QRGame#65]
I found the problem. The inventory is pulling the qr codes from the user database instead of the qr database, which means it will pull old copies of stuff. You need to use the qr codes from the database to get the comments. Try to use the getQrCode function on the databse controller.

**Comment by ArmannDeol** [comment]
Nullpointer exception when no qr codes in user

**Comment by ksj369** [comment]
fixed
